<package format="3">
  <name>hsrb_rosnav_config</name>
  <version>2.1.1</version>
  <description>The hsrb_rosnav_config package</description>

  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>
  <author email="dev@opensource-robotics.tokyo.jp">Tokyo Opensource Robotics Kyokai</author>
  <license>BSD 3-clause Clear License</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_rviz_plugins</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>